apiVersion: v1
kind: Pod
metadata: 
  name: test-pd
spec:
  containers:
  - image: nginx
    name: test-container
    ports:
    - containerPort: 80
      hostPort: 8081
    volumeMounts:
    - mountPath: /test-pd
      name: test-volume
  volumes:
  - name: test-volume
    hostPath:
      path: /opt/yml


