apiVersion: v1
kind: Pod
metadata:
  name: pod-emptydir
spec:
  containers:
  - image: wangyanglinux/myapp:v1   #网上找的镜像，可单独运行
    imagePullPolicy: IfNotPresent
    name: container1
    volumeMounts:
    - mountPath: /cache
      name: cache-volume
  - image: busybox
    name: container2
    imagePullPolicy: IfNotPresent
    command:    #这里的command必须要加，否则没有后台任务运行，容器启动就退出了
    - /bin/sh
    - -c
    - sleep 3600
    volumeMounts:
    - mountPath: /cache
      name: cache-volume
  volumes:
  - name: cache-volume
    emptyDir: {}


# 1.创建两个容器，将数据挂载到同一个目录下
# 2.在 container1 中的 /cache 文件夹下创建一个文件并写入数据，然后在 container2 中查看数据是否共享
