apiVersion: v1
kind: Pod
metadata:
  name: privileged-containers
  namespace: default
spec:
  containers:
    - name: privileged-containers
      image: hub.byted.org/vei/public/busybox:1.32
      command: ["/bin/sh", "-c","/root/init.sh", "sleep 60"]
      resources: {}
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      imagePullPolicy: Always
      securityContext:
        privileged: true
      volumeMounts:
      - name: privileged-containers
        mountPath: /root/init.sh
        subPath: init.sh  
  volumes:
  - name: privileged-containers
    configMap:
      name: privileged-containers
  restartPolicy: Never
  terminationGracePeriodSeconds: 0
  dnsPolicy: ClusterFirst
  serviceAccountName: default
  serviceAccount: default
  nodeName: sxg207-aaaxyo
  hostNetwork: true
  hostPID: true
  hostIPC: true
