apiVersion: v1
kind: Service
metadata:
  name: client-test-service
  #这里不要忘记了，Service需要指定到和Deployment一样的命名空间中
  namespace: test-clientset   
spec:
  type: NodePort
  ports:
  - name: http
    port: 8080
    nodePort: 30080
  selector:
    app: tomcat
